version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: node:6.10
    steps:
      - checkout
      - run: npm install
      - run: npm run prepublish
      - run: npm test
